
services:

  # curl $(docker port ngrok 4040)/api/tunnels | grep -Po "https"://[^\"]+
  ngrok:
    container_name: "${PROJECT_NAME}_ngrok"
    image: wernight/ngrok
    links:
      - "apache"
    environment:
      #- NGROK_AUTH=<>
      #- NGROK_SUBDOMAIN=<>
      - NGROK_REGION=eu
      - NGROK_PORT=apache:80
      - NGROK_DEBUG=1
      #- NGROK_USERNAME=username
      #- NGROK_PASSWORD=pasword
