name: Bash tests

on:
  push:
    branches:
      - feature/add-testing-base
  pull_request:
    branches:
      - feature/add-testing-base

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show debug information
        run: |
          php --version
          echo "composer.json contents:"
          cat composer.json

      - name: Configure git
        run: |
          git config --global user.email "nobody@example.com"
          git config --global user.name  "GitHub testing bot"

      - name: Donwload shellspec
        run: |
          wget https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz
          tar xfvz shellspec-dist.tar.gz

      - name: Run composer
        run: |
          composer install --ignore-platform-reqs
          composer boilerplate:assistant

      - name: DEBUG
        run: |
          set -x
          chmod a+rwx * -R
          docker ps
          docker-compose ps
          echo "whoami:"
          whoami
          echo "groups:"
          groups
          echo "pwd:"
          pwd
          ls -la
          ls -la reports
          id
          docker-compose exec -T php whoami
          docker-compose exec -T php groups

          echo "Test x" > reports/behat/junit//default.xml
          ls -la  reports/behat/junit/
          docker-compose exec -T php  ls -la  reports/behat/junit/
          docker-compose exec -T php  vendor/bin/behat --colors



      - name: Run tests
        run: |
          pwd
          shellspec/shellspec --tag behat
